apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "0.0.201"
          url: "docker.io/cbpautomation/python-hello-world-docker:0.0.201"
          digest: "sha256:8ceadae2aa3081d147dcbe764175a564bac3a8a0487d79d80c3fc3ed246653cf"
          target-environment: "PREPROD"